version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: bigdata_postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: bigdata

    ports:
      - "5432:5432"

    volumes:
      - ./data:/data
      - ./sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: